Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: No such option: --portrt Did you mean --port?
 * Serving Flask app 'app.py'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.31.30.112:5000
Press CTRL+C to quit
76.136.11.237 - - [29/Oct/2024 08:32:28] "GET /send HTTP/1.1" 405 -
76.136.11.237 - - [29/Oct/2024 08:32:30] "GET /send HTTP/1.1" 405 -
76.136.11.237 - - [29/Oct/2024 08:34:33] "GET / HTTP/1.1" 200 -
76.136.11.237 - - [29/Oct/2024 08:34:33] "GET /favicon.ico HTTP/1.1" 404 -
104.28.104.14 - - [29/Oct/2024 08:34:59] "GET / HTTP/1.1" 200 -
104.28.104.14 - - [29/Oct/2024 08:34:59] "GET /favicon.ico HTTP/1.1" 404 -
104.28.104.14 - - [29/Oct/2024 08:35:13] "GET / HTTP/1.1" 200 -
104.28.104.14 - - [29/Oct/2024 08:35:13] "GET /chat HTTP/1.1" 200 -
[2024-10-29 08:35:16,675] ERROR in app: Exception on /send [POST]
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/ec2-user/CryptoChat/app.py", line 31, in send_message
    iv, ciphertext, tag = encryptMessage(sharedSecret1, message)
NameError: name 'sharedSecret1' is not defined
104.28.104.14 - - [29/Oct/2024 08:35:16] "POST /send HTTP/1.1" 500 -
76.136.11.237 - - [29/Oct/2024 08:36:47] "GET / HTTP/1.1" 200 -
76.136.11.237 - - [29/Oct/2024 08:36:52] "GET /chat HTTP/1.1" 200 -
[2024-10-29 08:36:55,086] ERROR in app: Exception on /send [POST]
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/ec2-user/CryptoChat/app.py", line 31, in send_message
    iv, ciphertext, tag = encryptMessage(sharedSecret1, message)
NameError: name 'sharedSecret1' is not defined
76.136.11.237 - - [29/Oct/2024 08:36:55] "POST /send HTTP/1.1" 500 -
 * Serving Flask app 'app.py'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.31.30.112:5000
Press CTRL+C to quit
[2024-10-29 08:39:45,180] ERROR in app: Exception on /send [POST]
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/ec2-user/CryptoChat/app.py", line 31, in send_message
    iv, ciphertext, tag = encryptMessage(sharedSecret1, message)
NameError: name 'sharedSecret1' is not defined
76.136.11.237 - - [29/Oct/2024 08:39:45] "POST /send HTTP/1.1" 500 -
76.136.11.237 - - [29/Oct/2024 08:39:46] "GET /send HTTP/1.1" 405 -
76.136.11.237 - - [29/Oct/2024 08:39:56] "GET / HTTP/1.1" 200 -
76.136.11.237 - - [29/Oct/2024 08:40:02] "GET /chat HTTP/1.1" 200 -
[2024-10-29 08:40:04,779] ERROR in app: Exception on /send [POST]
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/ec2-user/CryptoChat/app.py", line 31, in send_message
    iv, ciphertext, tag = encryptMessage(sharedSecret1, message)
NameError: name 'sharedSecret1' is not defined
76.136.11.237 - - [29/Oct/2024 08:40:04] "POST /send HTTP/1.1" 500 -
